name: Syntax Check Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  syntax-check:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore NuGet sources
        run: dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org

      - name: Restore dependencies
        run: dotnet restore DentalClinic.sln

      - name: Run dotnet format
        run: dotnet format DentalClinic.sln --verify-no-changes
