name: Syntax Check Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  syntax-check:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2022buildtools -y --package-parameters "--includeRecommended --quiet --wait"

      - name: Install dotnet format
        run: dotnet tool install -g dotnet-format --version 7.0.0

      - name: Restore dependencies
        run: dotnet restore DentalClinic.sln

      - name: Run dotnet format
        run: dotnet format DentalClinic.sln --verify-no-changes
