name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    permissions:
        actions: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Powershell
      run: powershell
    
    
    - name: Download PMD
      run: Invoke-WebRequest -Uri "https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.8.0/pmd-dist-7.8.0-bin.zip" -OutFile ".\pmd-dist-7.8.0-bin.zip"
    
    - name: Unzip PMD
      run: Expand-Archive -Path ".\pmd-dist-7.8.0-bin.zip" -DestinationPath ".\pmd-dist-7.8.0-bin" -Force
    
    - name: CD to analyzer
      run: dir
    
    - name: Run
      run: pmd.bat -d ./ -f text -R csharp-design