name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    permissions:
      actions: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run powershell
      run: powershell
    
    - name: download dotnet
      run: curl -o dotnetfx472_full_x64.exe https://download.microsoft.com/download/5/7/6/5765D4A5-1D1F-4670-BD97-EB2A4D2D2E6D/dotnetfx472_full_x64.exe


    - name: install dotnet
      run: dotnetfx472_full_x64.exe /q /norestart
    
    - name: test msbuild
      run: .\dotnet msbuild

    - name: install Nuget
      run: Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile .\
    
    - name: nuget, install StyleCop.Analysis packages
      run: nuget install StyleCop.Analyzers -OutputDirectory packages
    
    - name: remove project end
      run: (Get-Content *.csproj) -replace '</Project>', ' ' | Out-File -encoding utf8 DentalClinic.csproj

    - name: add packages to file DentalClinic.csproj
      run: .\add_packages.bat
    
    - name: build project
      run: msbuild