name: Syntax Check Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  syntax-check:
    runs-on: windows-2022

    steps:
      # Шаг 1: Checkout репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run dotnet format
        run: dotnet format --verify-no-changes
        continue-on-error: false

      - name: Run Roslyn Analyzers
        run: dotnet build --no-restore /p:TreatWarningsAsErrors=true