name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    permissions:
      actions: write
    steps:

    - name: Run powershell
      run: powershell
    
    - name: download dotnet
      run: Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1

    - name: install dotnet
      run: .\dotnet-install.ps1 -Channel LTS -InstallDir .\
    
    - name: test msbuild
      run: .\dotnet msbuild

    - name: install Nuget
      run: Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile .\
    
    - name: nuget, install StyleCop.Analysis packages
      run: nuget install StyleCop.Analyzers -OutputDirectory packages
    
    - name: remove project end
      run: (Get-Content *.csproj) -replace '</Project>', ' ' | Out-File -encoding utf8 DentalClinic.csproj

    - name: add packages to file DentalClinic.csproj
      run: .\add_packages.bat
    
    - name: build project
      run: msbuild